### ISSUE TITLE
Does not report invalid relative links when invalid routing rules are provided

### ISSUE THREAD

**Issue by ep-linden** [parthpp/textlint-rule-no-dead-relative-link#23]
**Test Steps**
Provide routing rules with regex that do not match any of the invalid relative links in the config file. Then run `textlint-rule-no-dead-relative-link`.

**Expected Results**
See report from `textlint-rule-no-dead-relative-link` stating that the relative link is invalid.

**Actual Results**
The report is empty with no invalid relative links.

**Comment by pa-eps** [comment]
Released in v1.1.1
