### ISSUE TITLE
Broken links inside markdown blockquote should be reported as error

### ISSUE THREAD

**Issue by amimas** [parthpp/textlint-rule-no-dead-relative-link#4]
Currently this rule does not report an error if there is a broken link within a text that is inside a markdown blockquote. For example:

```markdown
    > If these property values do not exist in the settings.xml, the source code might not be following the guidelines at [Setup Guide](../setup-introduction.md).
```

The relative link in the above sample could be broken but the linter rule does not report it as an error. If I remove the blockquote (`>`) and write it as regular paragraph, then the broken link gets reported as error.

**Comment by parthpp** [comment]
Fixed in release 1.0.1 and now available on npm https://www.npmjs.com/package/textlint-rule-no-dead-relative-link
